### PR TITLE
Added feature to Add New Volunteer + UI fix on Shelter form

### PR DESCRIPTION
**Pull request by SwaggerKhan**
Fixes issue #30

### CODE REVIEW

**Comment by SwaggerKhan** [comment]
Should I also add a city field in the form, or by default only set to add user to the city of the person logged in?

**Comment by SwaggerKhan** [comment]
Will add caching in the next commit. Changes aren't reflecting in same session at the moment.

**Review by binnyva — CHANGES_REQUESTED** [review]
Hey - good job. Very readable code :-)

Need these changes...
- Password should have a confirmation field as well.
- Keep User Type 'volunteer' selected by default.
- Handle errors from backend better. Eg. if you leave MAD Email as empty, it causes issues. Or invalid phone number.
- Add validation for phone number.
- If User was added successfully, then take them back to user listing page.
- Add user button should be at the bottom - currently its at the top.

**Comment by SwaggerKhan** [comment]
Still TODO: phone validation, error handling, redirection

**Comment by SwaggerKhan** [comment]
TODO:
Phone number validation
Display server side validation errors

**Comment by SwaggerKhan** [comment]
TODO: Server side error displays

Made all other requested changes

**Comment by binnyva** [comment]
Looks good so far. For the form, use the same form structure that exists in madnet. Eg. See the new donation http://localhost:3000/#/donations/0 - it uses the standard UI convention we are using. Use that.

Also, don't have a default password. Just keep it empty.

**Comment by SwaggerKhan** [comment]
> Looks good so far. For the form, use the same form structure that exists in madnet. Eg. See the new donation http://localhost:3000/#/donations/0 - it uses the standard UI convention we are using. Use that.
> 
> Also, don't have a default password. Just keep it empty.

Got it. Will make the ui changes and remove the default password

**Pull request merged**
